import { motion } from "motion/react";
import { useState, type ReactNode } from "react";
import { AlertCircle, RefreshCw } from "lucide-react";
import { Button, Card } from "./ui";

export type Point={label:string;value:number;secondary?:number};
export const trend:Point[]=[{label:"06/01",value:72,secondary:28},{label:"06/05",value:86,secondary:35},{label:"06/09",value:79,secondary:31},{label:"06/13",value:108,secondary:42},{label:"06/17",value:104,secondary:48},{label:"06/21",value:132,secondary:55},{label:"06/25",value:149,secondary:61},{label:"06/30",value:166,secondary:72}];
const path=(data:Point[],key:"value"|"secondary"="value")=>data.map((p,i)=>`${i?"L":"M"} ${18+i*(284/(data.length-1))} ${150-(Number(p[key]??0)/Math.max(...data.map(d=>Number(d[key]??0))))*116}`).join(" ");

export function ChartCard({title,subtitle,children,error,onRetry}:{title:string;subtitle?:string;children:ReactNode;error?:string;onRetry?:()=>void}) { return <Card className="rbl-chart-card"><header><div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div><span className="rbl-live">LIVE</span></header>{error?<div className="rbl-chart-error"><AlertCircle/><b>{error}</b><Button onClick={onRetry}><RefreshCw size={13}/>重试</Button></div>:children}</Card>; }
export function AreaChart({title="播放与互动趋势",data=trend,onPoint}:{title?:string;data?:Point[];onPoint?:(p:Point)=>void}) { const [hover,setHover]=useState<number|null>(null);const [second,setSecond]=useState(true);return <ChartCard title={title} subtitle="悬停十字线 · 点击异常点下钻"><div className="rbl-legend"><Button className="active"><i/>播放</Button><Button className={second?"active":""} onClick={()=>setSecond(!second)}><i/>互动</Button></div><svg className="rbl-area" viewBox="0 0 320 180" role="img" aria-label={`${title}，最近 30 天总体增长`}><defs><linearGradient id={`fill-${title}`} x1="0" y1="0" x2="0" y2="1"><stop stopColor="#990099" stopOpacity=".32"/><stop offset="1" stopColor="#990099" stopOpacity="0"/></linearGradient></defs>{[34,72,110,148].map(y=><line key={y} x1="12" x2="308" y1={y} y2={y} className="rbl-gridline"/>)}<motion.path initial={{pathLength:0}} animate={{pathLength:1}} d={`${path(data)} L 302 156 L 18 156 Z`} fill={`url(#fill-${title})`}/><motion.path initial={{pathLength:0}} animate={{pathLength:1}} transition={{duration:1}} d={path(data)} className="rbl-line"/>{second&&<motion.path initial={{pathLength:0}} animate={{pathLength:1}} d={path(data,"secondary")} className="rbl-line secondary"/>}{data.map((p,i)=>{const x=18+i*(284/(data.length-1));const y=150-(p.value/Math.max(...data.map(d=>d.value)))*116;return <g key={p.label} onMouseEnter={()=>setHover(i)} onMouseLeave={()=>setHover(null)} onClick={()=>onPoint?.(p)} tabIndex={0}>{hover===i&&<line x1={x} x2={x} y1="25" y2="156" className="rbl-cross"/>}<circle cx={x} cy={y} r={i===5?6:4} className={i===5?"rbl-point anomaly":"rbl-point"}/>{hover===i&&<foreignObject x={Math.min(x,230)} y={Math.max(3,y-38)} width="84" height="34"><div className="rbl-tip">{p.label}<b>{p.value} 万</b></div></foreignObject>}</g>})}<rect x="72" y="163" width="178" height="8" rx="4" className="rbl-brush"/><rect x="128" y="160" width="76" height="14" rx="7" className="rbl-brush-active"/></svg></ChartCard>; }
export function Donut({title="流量来源",items=[46,24,18,12]}:{title?:string;items?:number[]}) { const [hover,setHover]=useState<number|null>(null);const colors=["#990099","#d43bd4","#7961d0","#7a727b"];let offset=0;return <ChartCard title={title}><div className="rbl-donut-layout"><svg viewBox="0 0 140 140">{items.map((v,i)=>{const dash=`${v} ${100-v}`,current=offset;offset+=v;return <motion.circle key={i} initial={{strokeDasharray:"0 100"}} animate={{strokeDasharray:dash}} cx="70" cy="70" r="48" pathLength="100" strokeDashoffset={-current} stroke={colors[i]} className="rbl-donut-ring" onMouseEnter={()=>setHover(i)} onMouseLeave={()=>setHover(null)}/>})}<text x="70" y="67" textAnchor="middle">{hover===null?"381万":`${items[hover]}%`}</text><text x="70" y="84" textAnchor="middle" className="sub">{hover===null?"总播放":"占比"}</text></svg><div className="rbl-donut-legend">{["首页推荐","站内搜索","关注动态","外部链接"].map((x,i)=><Button key={x} onClick={()=>setHover(i)}><i style={{background:colors[i]}}/>{x}<b>{items[i]}%</b></Button>)}</div></div></ChartCard>; }
export function Bars({title="内容分区表现",data=[82,74,63,51]}:{title?:string;data?:number[]}) { return <ChartCard title={title}><div className="rbl-bars">{data.map((v,i)=><div key={i}><motion.i initial={{height:0}} animate={{height:`${v}%`}} transition={{delay:i*.08}}/><span>{["动画","游戏","知识","生活"][i]}</span></div>)}</div></ChartCard>; }
export function Heatmap({title="发布时间热力图"}:{title?:string}) { return <ChartCard title={title}><div className="rbl-heat">{Array.from({length:42},(_,i)=><motion.button whileHover={{scale:1.4}} title={`活跃度 ${18+(i*17)%82}`} key={i} style={{opacity:.16+((i*17)%82)/100}}/>)}</div><div className="rbl-heat-label"><span>周一</span><span>周日</span></div></ChartCard>; }
export function Gauge({title="总池使用率",value=69,label="44 / 64 TB"}:{title?:string;value?:number;label?:string}) { return <ChartCard title={title}><div className="rbl-gauge"><svg viewBox="0 0 160 100"><path d="M 20 86 A 60 60 0 0 1 140 86" pathLength="100"/><motion.path initial={{pathLength:0}} animate={{pathLength:value/100}} d="M 20 86 A 60 60 0 0 1 140 86" className="fill"/></svg><strong>{value}%</strong><span>{label}</span></div></ChartCard>; }
export function Spark({points}:{points:number[]}) { const d=points.map((v,i)=>`${i?"L":"M"}${i*16},${32-v/2}`).join(" ");return <svg className="rbl-spark" viewBox="0 0 80 35"><motion.path initial={{pathLength:0}} animate={{pathLength:1}} d={d}/></svg>; }
