import { AnimatePresence, motion } from "motion/react";
import { Bell, ChevronLeft, Command, HelpCircle, LayoutDashboard, Menu, MessageCircle, Moon, Plus, Search, Settings, SlidersHorizontal, Sun, Zap } from "lucide-react";
import { useState, type ReactNode } from "react";
import { useNavigate } from "react-router-dom";
import { Button, Card, Chip, Input, Select } from "./ui";
import { Spark } from "./charts";

export type ModuleId="dashboard"|"quota"|"community"|"settings";
const nav:Array<[ModuleId,string,ReactNode]>=[["dashboard","企业数据总览",<LayoutDashboard/>],["quota","中转站额度",<SlidersHorizontal/>],["community","社区",<MessageCircle/>],["settings","设置",<Settings/>]];
export function Shell({module,theme,toggleTheme,children}:{module:ModuleId;theme:"light"|"dark";toggleTheme:()=>void;children:ReactNode}) {
 const navigate=useNavigate();const [collapsed,setCollapsed]=useState(false);const [command,setCommand]=useState(false);const [create,setCreate]=useState(false);
 return <div className={`rbl-app ${collapsed?"collapsed":""}`} data-theme={theme}><header className="rbl-top"><Button icon variant="ghost" onClick={()=>setCollapsed(!collapsed)}><Menu/></Button><div className="rbl-logo"><span><Zap/></span><b>BiliOps</b><Chip>React Bits</Chip></div><Button className="rbl-search" onClick={()=>setCommand(true)}><Search/><span>搜索工作台…</span><kbd><Command/>K</kbd></Button><div className="rbl-top-actions"><Button variant="primary" onClick={()=>setCreate(!create)}><Plus/>创建</Button><div className="rbl-create-wrap"><AnimatePresence>{create&&<motion.div className="rbl-create-menu" initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}}>{["上传视频","配置额度","发布帖子","邀请成员"].map(x=><Button key={x} onClick={()=>setCreate(false)}>{x}</Button>)}</motion.div>}</AnimatePresence></div><Button icon variant="ghost"><Bell/><i className="rbl-unread"/></Button><Button icon variant="ghost" onClick={toggleTheme}>{theme==="dark"?<Sun/>:<Moon/>}</Button><Button className="rbl-avatar">林</Button></div></header>
 <aside className="rbl-side"><div className="rbl-workspace"><span>星</span><div><b>星轨内容科技</b><small>企业工作区</small></div></div><nav>{nav.map(([id,label,icon])=><Button key={id} className={module===id?"active":""} onClick={()=>navigate(`/lab/react-bits/${id}`)}>{icon}<span>{label}</span>{id==="community"&&<Chip tone="warning">18</Chip>}</Button>)}</nav><div className="rbl-side-bottom"><Button><HelpCircle/><span>帮助与文档</span></Button><Button><i className="rbl-status"/><span>系统运行正常</span></Button><Select label="当前 UI 库" value="bits" options={[["bits","React Bits"]]} onChange={()=>{}}/></div></aside>
 <main className="rbl-content">{children}</main>
 <AnimatePresence>{command&&<motion.div className="rbl-command-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setCommand(false)}><motion.div className="rbl-command" initial={{scale:.96,y:-20}} animate={{scale:1,y:0}} onClick={e=>e.stopPropagation()}><div><Search/><Input aria-label="全局搜索" autoFocus placeholder="搜索页面、视频、成员和设置…"/></div>{nav.map(([id,label,icon])=><Button key={id} onClick={()=>{navigate(`/lab/react-bits/${id}`);setCommand(false)}}>{icon}{label}<span>跳转</span></Button>)}</motion.div></motion.div>}</AnimatePresence>
 </div>;
}
export function PageHeader({eyebrow,title,description,actions}:{eyebrow:string;title:string;description:string;actions:ReactNode}) { const [range,setRange]=useState("30d");return <><div className="rbl-page-head"><div><span>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div><div>{actions}</div></div><div className="rbl-toolbar"><div><Chip tone="success">实时数据</Chip><span>最近同步 2 分钟前</span></div><div><Select label="时间范围" value={range} options={[["7d","近 7 天"],["30d","近 30 天"],["90d","近 90 天"]]} onChange={setRange}/><Button><ChevronLeft className="rbl-refresh"/>刷新</Button></div></div></>; }
export function KPI({label,value,delta,icon,points}:{label:string;value:string;delta:string;icon:ReactNode;points:number[]}) { return <Card className="rbl-kpi"><header><span>{label}</span><i>{icon}</i></header><strong>{value}</strong><footer><Chip tone="success">↑ {delta}</Chip><Spark points={points}/></footer></Card>; }
