import { AnimatePresence, motion, type HTMLMotionProps } from "motion/react";
import { Check, ChevronDown, LoaderCircle, X } from "lucide-react";
import { useState, type ReactNode } from "react";

export function Button({ children, onClick, variant="default", disabled=false, type="button", icon=false, className="" }: { children:ReactNode;onClick?:()=>void;variant?:"default"|"primary"|"ghost"|"danger";disabled?:boolean;type?:"button"|"submit";icon?:boolean;className?:string }) {
  return <motion.button whileHover={disabled?undefined:{y:-1}} whileTap={disabled?undefined:{scale:.96}} className={`rbl-button ${variant} ${icon?"icon":""} ${className}`} type={type} disabled={disabled} onClick={onClick}>{children}</motion.button>;
}
export function AsyncButton({ children, pending, onClick }: {children:ReactNode;pending:boolean;onClick:()=>void}) { return <Button variant="primary" disabled={pending} onClick={onClick}>{pending?<LoaderCircle className="rbl-spin" size={15}/>:null}{children}</Button>; }
export function Card({ children, className="" }: {children:ReactNode;className?:string}) { return <motion.section initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} className={`rbl-card ${className}`}>{children}</motion.section>; }
export function Chip({children,tone="accent"}:{children:ReactNode;tone?:"accent"|"success"|"warning"|"danger"}) { return <span className={`rbl-chip ${tone}`}>{children}</span>; }
export function Field({label,children,msg}:{label:string;children:ReactNode;msg?:string}) { return <label className="rbl-field"><span>{label}</span>{children}{msg&&<small>{msg}</small>}</label>; }
export function Input(props: HTMLMotionProps<"input">) { return <motion.input whileFocus={{scale:1.005}} {...props}/>; }
export function Textarea(props: HTMLMotionProps<"textarea">) { return <motion.textarea whileFocus={{scale:1.005}} {...props}/>; }
export function Select({label,value,options,onChange}:{label:string;value:string;options:Array<[string,string]>;onChange:(value:string)=>void}) {
  const [open,setOpen]=useState(false);const selected=options.find(([id])=>id===value)?.[1];
  return <div className="rbl-select"><span>{label}</span><Button className="rbl-select-trigger" onClick={()=>setOpen(!open)}>{selected}<ChevronDown size={14}/></Button><AnimatePresence>{open&&<motion.div className="rbl-select-menu" initial={{opacity:0,y:-7}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-7}}>{options.map(([id,text])=><Button key={id} className={id===value?"selected":""} onClick={()=>{onChange(id);setOpen(false)}}>{text}{id===value&&<Check size={13}/>}</Button>)}</motion.div>}</AnimatePresence></div>;
}
export function Switch({checked,onChange,label,detail}:{checked:boolean;onChange:(value:boolean)=>void;label:string;detail?:string}) { return <Button className="rbl-switch-row" onClick={()=>onChange(!checked)}><span className={`rbl-switch ${checked?"on":""}`}><i/></span><span><b>{label}</b>{detail&&<small>{detail}</small>}</span></Button>; }
export function Segments({value,items,onChange}:{value:string;items:Array<[string,string]>;onChange:(value:string)=>void}) { return <div className="rbl-segments">{items.map(([id,label])=><Button key={id} className={value===id?"active":""} onClick={()=>onChange(id)}>{label}</Button>)}</div>; }
export function Alert({error,onRetry}:{error:AppError;onRetry?:()=>void}) { return <motion.div className="rbl-alert" initial={{opacity:0,height:0}} animate={{opacity:1,height:"auto"}}><div><b>{error.code}</b><p>{error.msg}</p>{error.requestId&&<small>请求 ID：{error.requestId}</small>}</div>{error.retryable&&onRetry&&<Button variant="danger" onClick={onRetry}>重试</Button>}</motion.div>; }
export function Dialog({open,title,children,onClose}:{open:boolean;title:string;children:ReactNode;onClose:()=>void}) { return <AnimatePresence>{open&&<motion.div className="rbl-overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={onClose}><motion.div className="rbl-dialog" initial={{scale:.94,y:15}} animate={{scale:1,y:0}} exit={{scale:.96,y:10}} onMouseDown={e=>e.stopPropagation()}><header><h2>{title}</h2><Button icon variant="ghost" onClick={onClose}><X size={18}/></Button></header>{children}</motion.div></motion.div>}</AnimatePresence>; }
export function Drawer({open,title,children,onClose}:{open:boolean;title:string;children:ReactNode;onClose:()=>void}) { return <AnimatePresence>{open&&<><motion.div className="rbl-drawer-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={onClose}/><motion.aside className="rbl-drawer" initial={{x:"100%"}} animate={{x:0}} exit={{x:"100%"}}><header><h2>{title}</h2><Button icon variant="ghost" onClick={onClose}><X size={18}/></Button></header>{children}</motion.aside></>}</AnimatePresence>; }
export function Table({columns,rows}:{columns:string[];rows:ReactNode[][]}) { return <div className="rbl-table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((row,i)=><motion.tr key={i} initial={{opacity:0}} animate={{opacity:1}} transition={{delay:i*.04}}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</motion.tr>)}</tbody></table></div>; }
export type AppError={code:string;msg:string;fieldErrors?:Record<string,string>;requestId?:string;retryable:boolean};
