import { motion } from "motion/react";
import { AlertTriangle, RotateCcw, TrendingUp } from "lucide-react";
import { useMemo, useState, type ReactNode } from "react";
import { Button, Card, CardHead, Chip } from "./ui";
import type { ChartPoint } from "./types";

export function MetricCard({label,value,delta,points,icon,onClick}:{label:string;value:string;delta:string;points:number[];icon:ReactNode;onClick?:()=>void}) { const max=Math.max(...points),min=Math.min(...points);const line=points.map((v,i)=>`${i*25},${38-((v-min)/Math.max(1,max-min))*30}`).join(" ");return <motion.button className="acl-metric" onClick={onClick} whileHover={{y:-3}}><header><span>{label}</span><i>{icon}</i></header><strong>{value}</strong><small><TrendingUp/> {delta}</small><svg viewBox="0 0 150 42" role="img" aria-label={`${label}趋势`}><polyline points={line}/></svg></motion.button>; }

export function AreaChart({title,subtitle,data,series=["播放","互动"],error,onRetry,onDrilldown}:{title:string;subtitle?:string;data:ChartPoint[];series?:string[];error?:string;onRetry?:()=>void;onDrilldown?:(p:ChartPoint)=>void}) { const [hover,setHover]=useState<number|null>(null),[visible,setVisible]=useState([true,true]);const max=useMemo(()=>Math.max(...data.flatMap(x=>[x.value,x.secondary??0])),[data]);const coords=(key:"value"|"secondary")=>data.map((x,i)=>`${18+i*(462/Math.max(1,data.length-1))},${178-((x[key]??0)/max)*145}`).join(" ");return <Card className="acl-chart" glow><CardHead title={title} subtitle={subtitle} action={<div className="acl-legend">{series.map((s,i)=><Button key={s} className={visible[i]?"selected":""} onClick={()=>setVisible(v=>v.map((x,n)=>n===i?!x:x))}><i className={`dot-${i}`}/>{s}</Button>)}</div>}/>{error?<div className="acl-chart-error"><AlertTriangle/><b>图表加载失败</b><span>{error}</span><Button kind="outline" onClick={onRetry}><RotateCcw/>重试</Button></div>:<><div className="acl-area" onMouseLeave={()=>setHover(null)}><svg viewBox="0 0 500 210" role="img" aria-label={title} tabIndex={0} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();setHover(Math.max(0,Math.min(data.length-1,Math.round((e.clientX-r.left)/r.width*(data.length-1)))));}} onClick={()=>hover!==null&&onDrilldown?.(data[hover])}><defs><linearGradient id={`acl-${title}`} x1="0" y1="0" x2="0" y2="1"><stop stopColor="#990099" stopOpacity=".38"/><stop offset="1" stopColor="#990099" stopOpacity="0"/></linearGradient></defs>{[42,88,134,180].map(y=><line key={y} x1="18" x2="482" y1={y} y2={y} className="acl-gridline"/>)}{visible[0]&&<><polygon points={`18,178 ${coords("value")} 480,178`} fill={`url(#acl-${title})`}/><polyline points={coords("value")} className="acl-line"/></>}{visible[1]&&<polyline points={coords("secondary")} className="acl-line acl-line--secondary"/>}{hover!==null&&<><line x1={18+hover*462/Math.max(1,data.length-1)} x2={18+hover*462/Math.max(1,data.length-1)} y1="28" y2="180" className="acl-cross"/><circle cx={18+hover*462/Math.max(1,data.length-1)} cy={178-data[hover].value/max*145} r="5" className="acl-point"/></>}</svg>{hover!==null&&<motion.div className="acl-tooltip" initial={{opacity:0}} animate={{opacity:1}}><b>{data[hover].label}</b><span>{series[0]} {data[hover].value.toLocaleString()}</span><span>{series[1]} {(data[hover].secondary??0).toLocaleString()}</span><small>点击查看下钻</small></motion.div>}</div><div className="acl-brush"><span/><i/></div></>}</Card>; }

export function DonutChart({title,data}:{title:string;data:Array<{label:string;value:number;color:string}>}) { const [active,setActive]=useState(0);const total=data.reduce((s,x)=>s+x.value,0);let start=0;const gradient=data.map(x=>{const from=start;start+=x.value/total*100;return `${x.color} ${from}% ${start}%`;}).join(",");return <Card className="acl-chart"><CardHead title={title} action={<Chip>实时</Chip>}/><div className="acl-donut-layout"><motion.div className="acl-donut" animate={{rotate:360}} transition={{duration:1,ease:"easeOut"}} style={{background:`conic-gradient(${gradient})`}}><div><strong>{data[active].value}%</strong><span>{data[active].label}</span></div></motion.div><div className="acl-donut-legend">{data.map((x,i)=><Button key={x.label} className={active===i?"selected":""} onClick={()=>setActive(i)}><i style={{background:x.color}}/>{x.label}<b>{x.value}%</b></Button>)}</div></div></Card>; }
export function BarChart({title,data}:{title:string;data:Array<{label:string;value:number;secondary?:number}>}) { const max=Math.max(...data.map(x=>x.value));return <Card className="acl-chart"><CardHead title={title} action={<Chip>占比</Chip>}/><div className="acl-bars">{data.map((x,i)=><Button className="acl-bar" key={x.label} title={`${x.label}：${x.value}，对比 ${x.secondary??0}`}><span>{x.label}</span><div><motion.i initial={{width:0}} whileInView={{width:`${x.value/max*100}%`}} viewport={{once:true}} transition={{delay:i*.08}}/><em style={{width:`${(x.secondary??0)/max*100}%`}}/></div><b>{x.value}</b></Button>)}</div></Card>; }
export function Heatmap({title,values,onSelect}:{title:string;values:number[];onSelect?:(i:number)=>void}) { return <Card className="acl-chart"><CardHead title={title} subtitle="星期 × 时段"/><div className="acl-heatmap">{values.map((v,i)=><motion.button key={i} aria-label={`热力值 ${v}`} title={`周${["一","二","三","四","五","六","日"][Math.floor(i/6)]} ${i%6*4}:00 · 活跃 ${v}`} style={{background:`rgba(153,0,153,${.12+v/120})`}} whileHover={{scale:1.16,zIndex:2}} onClick={()=>onSelect?.(i)}/>)}</div><div className="acl-heatlabels"><span>00:00</span><span>08:00</span><span>16:00</span><span>24:00</span></div></Card>; }
export function RadialGauge({title,value,label}:{title:string;value:number;label:string}) { return <Card className="acl-chart"><CardHead title={title}/><div className="acl-radial" style={{background:`conic-gradient(#990099 ${value}%,var(--acl-soft) 0)`}}><div><strong>{value}%</strong><span>{label}</span></div></div></Card>; }
export function FunnelChart({title,data}:{title:string;data:Array<{label:string;value:number}>}) { const [active,setActive]=useState(0),max=data[0]?.value??1;return <Card className="acl-chart"><CardHead title={title} action={<Chip tone="neutral">转化 {Math.round(data.at(-1)!.value/max*100)}%</Chip>}/><div className="acl-funnel">{data.map((x,i)=><Button key={x.label} className={active===i?"selected":""} style={{width:`${42+x.value/max*58}%`}} onClick={()=>setActive(i)}><span>{x.label}</span><b>{x.value.toLocaleString()}</b></Button>)}</div></Card>; }
export function ScatterChart({title,data}:{title:string;data:Array<{x:number;y:number;label:string}>}) { return <Card className="acl-chart"><CardHead title={title} subtitle="延迟 × 成功率"/><svg className="acl-scatter" viewBox="0 0 300 180" role="img" aria-label={title}>{[40,80,120,160].map(y=><line key={y} x1="15" x2="290" y1={y} y2={y} className="acl-gridline"/>)}{data.map(x=><circle key={x.label} cx={20+x.x*2.4} cy={165-x.y*1.4} r="7"><title>{x.label} · {x.x}ms · {x.y}%</title></circle>)}</svg></Card>; }
