import { BarChart3, Heart, Image, MessageCircle, MoreHorizontal, Plus, Send, Video, WandSparkles } from "lucide-react";
import { useState } from "react";
import { AreaChart, DonutChart, Heatmap, RadialGauge } from "./charts";
import { Button, Card, CardHead, Checkbox, Chip, DataTable, InlineAlert, PageHeader, Tabs, Textarea, Toast } from "./ui";
import { heatValues, trend, type AppError } from "./types";

export default function CommunityRoute() {
  const [liked,setLiked]=useState(false),[message,setMessage]=useState(""),[mode,setMode]=useState("rich"),[error,setError]=useState<AppError|null>(null),[toast,setToast]=useState("");
  const publish=()=>{if(message.includes("内部接口")){setError({code:"POST_REJECTED",msg:"内容包含受限词“内部接口”，请修改后重新发布。",fieldErrors:{content:"请移除受限词“内部接口”"},retryable:false});return;}setError(null);setToast("帖子发布成功，内容已进入社区最新动态。");setMessage("");};
  const toggleLike=()=>{setLiked(v=>!v);if(!liked&&message==="fail-like"){window.setTimeout(()=>{setLiked(false);setToast("点赞未同步：网络波动，请稍后重试。")},450)}};
  const reports=[["疑似引战评论","人身攻击","高","24","林岚"],["外链推广内容","广告垃圾","中","12","周可"],["剧透未标记","社区规范","低","6","未分配"]];
  return <div className="acl-page"><PageHeader eyebrow="COMMUNITY OPERATIONS" title="社区" description="发布内容、回复用户并治理风险讨论。" actions={<Button kind="primary"><Plus/>发布帖子</Button>} toolbar={<><Button className="selected">全部内容</Button><Button>待处理 18</Button><Button>我的草稿 3</Button></>}/>{error&&<InlineAlert error={error}/>}<section className="acl-community"><div className="acl-feed"><Card className="acl-composer" glow><div className="acl-author"><span>星</span><div><b>星轨内容科技</b><small>以组织身份发布</small></div></div><Tabs value={mode} onChange={setMode} items={[["rich","富文本"],["markdown","Markdown"]]}/><Textarea value={message} onChange={e=>setMessage(e.target.value)} rows={5} aria-label="帖子正文" placeholder={mode==="rich"?"分享新鲜事，输入“内部接口”可测试错误 msg…":"# 使用 Markdown 创作"}/>{error?.fieldErrors?.content&&<small className="acl-field-error">{error.fieldErrors.content}</small>}<div className="acl-composer-tools"><div><Button aria-label="添加图片"><Image/></Button><Button aria-label="添加视频"><Video/></Button><Button aria-label="添加投票"><BarChart3/></Button><Chip tone="neutral">{message.length}/500</Chip></div><Button kind="primary" onClick={publish}><Send/>发布</Button></div></Card>{[{name:"像素工坊",time:"18 分钟前",text:"独立游戏开发日志第 12 期上线了！这次重点拆解角色状态机与光照优化。",tag:"#独立游戏"},{name:"科技研习社",time:"1 小时前",text:"我们整理了生成式 AI 在视频工作流中的五个真实落地点，欢迎补充。",tag:"#AI创作"}].map((post,index)=><Card className="acl-post" key={post.name}><div className="acl-author"><span>{post.name[0]}</span><div><b>{post.name}</b><small>{post.time}</small></div><Button aria-label="更多"><MoreHorizontal/></Button></div><p>{post.text}</p><Chip>{post.tag}</Chip>{index===0&&<div className="acl-post-media"><WandSparkles/><b>DEVLOG · EP12</b></div>}<footer><Button className={liked&&index===0?"selected":""} onClick={()=>index===0&&toggleLike()}><Heart fill={liked&&index===0?"currentColor":"none"}/>{liked&&index===0?129:128}</Button><Button><MessageCircle/>36</Button><Button><Send/>分享</Button></footer></Card>)}</div><aside className="acl-community-aside"><RadialGauge title="社区健康度" value={92} label="稳定"/><AreaChart title="发帖趋势" data={trend.slice(0,6)} series={["帖子","回复"]}/><DonutChart title="热门话题" data={[{label:"游戏",value:34,color:"#990099"},{label:"科技",value:28,color:"#d23ad2"},{label:"生活",value:22,color:"#7750c7"},{label:"其他",value:16,color:"#6b7280"}]}/><Heatmap title="社区活跃" values={heatValues}/></aside></section><Card className="acl-table-card"><CardHead title="举报与治理" action={<Chip tone="warning">18 待处理</Chip>}/><DataTable label="举报与治理" columns={[<Checkbox label="全选"/>,"内容","原因","风险","举报数","处理人","操作"]} rows={reports.map(row=>[<Checkbox label={`选择 ${row[0]}`}/>,...row,<Button kind="outline">处理</Button>])}/></Card>{toast&&<Toast message={toast} tone={toast.includes("未同步")?"danger":"success"} onClose={()=>setToast("")}/>}</div>;
}
