import { AnimatePresence, motion } from "motion/react";
import { useLocation, useNavigate } from "react-router-dom";
import { Activity, Bell, Bot, ChevronDown, ChevronLeft, Gauge, HelpCircle, LayoutDashboard, Menu, MessageCircle, Moon, Plus, Search, Settings, Sun, Upload, UserPlus, Users, Video, X, Zap } from "lucide-react";
import { useState } from "react";
import { useTheme } from "@/lib/use-theme";
import DashboardRoute from "./dashboard";
import QuotaRoute from "./quota";
import CommunityRoute from "./community";
import SettingsRoute from "./settings";
import { BarChart } from "./charts";
import { AsyncButton, AvatarButton, Button, Chip, Drawer, Field, InlineAlert, Input, SearchInput, Select, Slider, Switch, Toast } from "./ui";
import type { AppError, ChartPoint, ModuleId } from "./types";
import "./styles.css";

const nav=[{id:"dashboard" as const,label:"企业数据总览",icon:LayoutDashboard},{id:"quota" as const,label:"中转站额度",icon:Gauge},{id:"community" as const,label:"社区",icon:MessageCircle},{id:"settings" as const,label:"设置",icon:Settings}];
const createItems=[{icon:Upload,label:"上传视频"},{icon:Gauge,label:"配置额度"},{icon:MessageCircle,label:"发布帖子"},{icon:UserPlus,label:"邀请成员"}];

function QuotaDrawer({open,onClose,onSaved}:{open:boolean;onClose:()=>void;onSaved:(msg:string)=>void}) { const [quota,setQuota]=useState(12000),[threshold,setThreshold]=useState(80),[route,setRoute]=useState("east"),[renew,setRenew]=useState(true),[state,setState]=useState<"idle"|"pending"|"success"|"error">("idle"),error:AppError|null=quota<8420?{code:"QUOTA_BELOW_USAGE",msg:"新额度不能低于当前已使用额度 8,420 GB。",fieldErrors:{quota:"最低可配置额度为 8,420 GB"},retryable:false}:null;const save=()=>{if(error){setState("error");return}setState("pending");window.setTimeout(()=>{setState("success");onSaved("额度配置已保存，新规则将在 1 分钟内生效。");window.setTimeout(onClose,500)},800)};return <Drawer open={open} onClose={onClose} title="配置额度池" footer={<><Button onClick={onClose}>取消</Button><AsyncButton state={state} onClick={save}>{state==="pending"?"保存中…":state==="success"?"已保存":"保存配置"}</AsyncButton></>}><div className="acl-drawer-form">{error&&<InlineAlert error={error}/>}<Field label="额度池名称"><Input defaultValue="视频理解组"/></Field><Field label="适用团队"><Select label="适用团队" value="video" onChange={()=>{}} options={[["video","视频理解组"],["recommend","推荐算法组"],["safety","内容安全组"]]}/></Field><Field label="总额度（GB）" error={error?.fieldErrors?.quota}><Input type="number" value={quota} min={0} onChange={e=>{setQuota(Number(e.target.value));setState("idle")}}/></Field><Field label={`预警阈值：${threshold}%`}><Slider label="预警阈值" value={threshold} min={50} max={95} onChange={setThreshold}/></Field><Field label="节点路由"><Select label="节点路由" value={route} onChange={setRoute} options={[["east","华东 A"],["north","华北 B"],["public","公共池"]]}/></Field><Switch checked={renew} onChange={setRenew} label="自动续期" description="结算周期结束后恢复额度。"/><details className="acl-accordion"><summary>高级限制</summary><p>并发上限 40，超额时借用公共池。</p></details></div></Drawer>; }

export default function BiliOpsAceternity() {
  const {theme,toggleTheme}=useTheme(),navigate=useNavigate(),location=useLocation();const candidate=location.pathname.split("/").pop();const module:ModuleId=nav.some(x=>x.id===candidate)?candidate as ModuleId:"dashboard";
  const [collapsed,setCollapsed]=useState(false),[mobile,setMobile]=useState(false),[search,setSearch]=useState(false),[create,setCreate]=useState(false),[notifications,setNotifications]=useState(false),[drawer,setDrawer]=useState(false),[detail,setDetail]=useState<ChartPoint|null>(null),[toast,setToast]=useState("");
  const go=(id:ModuleId)=>{navigate(`/lab/aceternity/${id}`);setMobile(false);setSearch(false)};
  return <div className={`acl-app ${collapsed?"is-collapsed":""}`} data-theme={theme}><header className="acl-topbar"><div className="acl-logo"><Button className="acl-mobile-menu" aria-label="打开导航" onClick={()=>setMobile(!mobile)}><Menu/></Button><span><Bot/></span><b>BiliOps</b><Chip>Aceternity</Chip></div><div className="acl-search"><Search/><SearchInput placeholder="搜索视频、用户、配置…" onFocus={()=>setSearch(true)}/><kbd>⌘ K</kbd><AnimatePresence>{search&&<motion.div className="acl-command" initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}}><header><span>快速跳转</span><Button onClick={()=>setSearch(false)}><X/></Button></header>{nav.map(item=><Button key={item.id} onClick={()=>go(item.id)}><item.icon/>{item.label}<kbd>↵</kbd></Button>)}</motion.div>}</AnimatePresence></div><div className="acl-top-actions"><div className="acl-popover-wrap"><Button kind="primary" onClick={()=>setCreate(!create)}><Plus/>创建<ChevronDown/></Button><AnimatePresence>{create&&<motion.div className="acl-popover" initial={{opacity:0,y:-7}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-7}}>{createItems.map(item=>{const CreateIcon=item.icon;return <Button key={item.label} onClick={()=>{setCreate(false);setToast(`已选择：${item.label}`)}}><CreateIcon/>{item.label}</Button>})}</motion.div>}</AnimatePresence></div><div className="acl-popover-wrap"><Button aria-label="通知" className="acl-bell" onClick={()=>setNotifications(!notifications)}><Bell/><i>3</i></Button><AnimatePresence>{notifications&&<motion.div className="acl-popover acl-notifications" initial={{opacity:0,y:-7}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-7}}><b>通知</b><div><strong>额度即将耗尽</strong><span>视频理解组已使用 80%</span></div><div><strong>新举报待处理</strong><span>社区收到 18 条举报</span></div></motion.div>}</AnimatePresence></div><Button aria-label="切换主题" onClick={toggleTheme}>{theme==="dark"?<Sun/>:<Moon/>}</Button><AvatarButton label="用户菜单">HX</AvatarButton></div></header>
    <AnimatePresence>{mobile&&<motion.div className="acl-mobile-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setMobile(false)}/>}</AnimatePresence><aside className={`acl-sidebar ${mobile?"is-mobile-open":""}`}><div className="acl-workspace"><span>星</span>{!collapsed&&<div><b>星轨内容科技</b><small>企业工作区</small></div>}</div><nav>{nav.map(item=><Button title={item.label} key={item.id} className={module===item.id?"selected":""} onClick={()=>go(item.id)}><item.icon/>{!collapsed&&<span>{item.label}</span>}{!collapsed&&item.id==="community"&&<Chip tone="warning">18</Chip>}</Button>)}</nav><div className="acl-side-bottom"><Button><HelpCircle/>{!collapsed&&"帮助与文档"}</Button><Button><Activity/>{!collapsed&&"系统状态"}</Button><Button onClick={()=>setCollapsed(!collapsed)}><ChevronLeft className={collapsed?"rotate":""}/>{!collapsed&&"收起侧栏"}</Button></div></aside>
    <main className="acl-content">{module==="dashboard"&&<DashboardRoute onDetail={setDetail}/>} {module==="quota"&&<QuotaRoute onConfigure={()=>setDrawer(true)}/>} {module==="community"&&<CommunityRoute/>} {module==="settings"&&<SettingsRoute/>}</main>
    <QuotaDrawer open={drawer} onClose={()=>setDrawer(false)} onSaved={setToast}/><Drawer open={Boolean(detail)} onClose={()=>setDetail(null)} title={`${detail?.label??"趋势"} 数据下钻`} footer={<><Button kind="outline" onClick={()=>setDetail(null)}>关闭</Button><Button kind="primary">查看完整报告</Button></>}><div className="acl-detail-value"><span>播放量</span><strong>{detail?.value.toLocaleString()}</strong></div><div className="acl-insight"><Zap/><div><b>检测到异常增长</b><span>首页推荐流量较日均水平高 28%，主要来自 3 个科技类视频。</span></div></div><BarChart title="来源拆解" data={[{label:"首页",value:82},{label:"搜索",value:48},{label:"关注",value:31},{label:"外链",value:18}]}/></Drawer>{toast&&<Toast message={toast} onClose={()=>setToast("")}/>}</div>;
}
