import { AnimatePresence, motion, type HTMLMotionProps } from "motion/react";
import { AlertTriangle, Check, ChevronDown, LoaderCircle, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import type { AppError } from "./types";

export function Button({children,kind="ghost",className="",...props}:HTMLMotionProps<"button">&{children:ReactNode;kind?:"primary"|"ghost"|"outline"|"danger"}) {
  return <motion.button {...props} className={`acl-button acl-button--${kind} ${className}`} whileHover={props.disabled?undefined:{y:-1}} whileTap={props.disabled?undefined:{scale:.97}}>{children}</motion.button>;
}
export function Card({children,className="",glow=false}:{children:ReactNode;className?:string;glow?:boolean}) {
  return <section className={`acl-card ${glow?"acl-card--glow":""} ${className}`}>{glow&&<span className="acl-card__beam" aria-hidden="true"/>}<div className="acl-card__inner">{children}</div></section>;
}
export function CardHead({title,subtitle,action}:{title:string;subtitle?:string;action?:ReactNode}) { return <header className="acl-card-head"><div><h3>{title}</h3>{subtitle&&<p>{subtitle}</p>}</div>{action}</header>; }
export function Chip({children,tone="accent"}:{children:ReactNode;tone?:"accent"|"success"|"warning"|"danger"|"neutral"}) { return <span className={`acl-chip acl-chip--${tone}`}>{children}</span>; }
export function InlineAlert({error,onRetry}:{error:AppError;onRetry?:()=>void}) { return <motion.div className="acl-alert" initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} role="alert"><AlertTriangle/><div><b>{error.code}</b><span>{error.msg}</span>{error.requestId&&<small>Request ID · {error.requestId}</small>}</div>{error.retryable&&onRetry&&<Button kind="outline" onClick={onRetry}>重试</Button>}</motion.div>; }
export function Field({label,error,children}:{label:string;error?:string;children:ReactNode}) { return <label className={`acl-field ${error?"is-invalid":""}`}><span>{label}</span>{children}{error&&<small>{error}</small>}</label>; }
export function Input(props:React.InputHTMLAttributes<HTMLInputElement>) { return <input className="acl-input" {...props}/>; }
export function Textarea(props:React.TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea className="acl-input acl-textarea" {...props}/>; }
export function Select({value,onChange,options,label}:{value:string;onChange:(v:string)=>void;options:Array<[string,string]>;label:string}) { const [open,setOpen]=useState(false);return <div className="acl-select"><Button kind="outline" aria-haspopup="listbox" aria-expanded={open} onClick={()=>setOpen(!open)}>{options.find(x=>x[0]===value)?.[1]??label}<ChevronDown/></Button><AnimatePresence>{open&&<motion.div className="acl-select__menu" role="listbox" initial={{opacity:0,y:-8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-8}}>{options.map(([id,text])=><Button key={id} role="option" aria-selected={id===value} className={id===value?"selected":""} onClick={()=>{onChange(id);setOpen(false)}}>{text}{id===value&&<Check/>}</Button>)}</motion.div>}</AnimatePresence></div>; }
export function Switch({checked,onChange,label,description}:{checked:boolean;onChange:(v:boolean)=>void;label:string;description?:string}) { return <Button className="acl-switch-row" role="switch" aria-checked={checked} onClick={()=>onChange(!checked)}><i className={checked?"checked":""}><span/></i><span><b>{label}</b>{description&&<small>{description}</small>}</span></Button>; }
export function Tabs({value,onChange,items}:{value:string;onChange:(v:string)=>void;items:Array<[string,string]>}) { return <div className="acl-tabs" role="tablist">{items.map(([id,label])=><Button key={id} role="tab" aria-selected={value===id} className={value===id?"selected":""} onClick={()=>onChange(id)}>{label}</Button>)}</div>; }
export function AsyncButton({state,children,onClick}:{state:"idle"|"pending"|"success"|"error";children:ReactNode;onClick?:()=>void}) { return <Button kind="primary" className={`acl-async is-${state}`} disabled={state==="pending"} onClick={onClick}>{state==="pending"?<LoaderCircle className="acl-spin"/>:state==="success"?<Check/>:state==="error"?<X/>:null}{children}</Button>; }
export function Modal({open,onClose,title,children,footer}:{open:boolean;onClose:()=>void;title:string;children:ReactNode;footer?:ReactNode}) { return <AnimatePresence>{open&&<motion.div className="acl-overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={onClose}><motion.div className="acl-modal" role="dialog" aria-modal="true" aria-label={title} initial={{opacity:0,scale:.96,y:18}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:.96}} onMouseDown={e=>e.stopPropagation()}><header><h2>{title}</h2><Button aria-label="关闭" onClick={onClose}><X/></Button></header><div className="acl-modal__body">{children}</div>{footer&&<footer>{footer}</footer>}</motion.div></motion.div>}</AnimatePresence>; }
export function Drawer({open,onClose,title,children,footer}:{open:boolean;onClose:()=>void;title:string;children:ReactNode;footer?:ReactNode}) { return <AnimatePresence>{open&&<motion.div className="acl-overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={onClose}><motion.aside className="acl-drawer" role="dialog" aria-modal="true" aria-label={title} initial={{x:"100%"}} animate={{x:0}} exit={{x:"100%"}} transition={{type:"spring",damping:28,stiffness:260}} onMouseDown={e=>e.stopPropagation()}><header><h2>{title}</h2><Button aria-label="关闭" onClick={onClose}><X/></Button></header><div className="acl-drawer__body">{children}</div>{footer&&<footer>{footer}</footer>}</motion.aside></motion.div>}</AnimatePresence>; }
export function Toast({message,tone="success",onClose}:{message:string;tone?:"success"|"danger";onClose:()=>void}) { return <motion.div className={`acl-toast is-${tone}`} role="status" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><span>{tone==="success"?<Check/>:<AlertTriangle/>}</span><b>{message}</b><Button aria-label="关闭消息" onClick={onClose}><X/></Button></motion.div>; }
export function PageHeader({eyebrow,title,description,actions,toolbar}:{eyebrow:string;title:string;description:string;actions:ReactNode;toolbar?:ReactNode}) { return <><div className="acl-page-header"><div><span>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div><div className="acl-page-actions">{actions}</div></div><div className="acl-toolbar"><div><Chip tone="success">实时数据</Chip><span>最近同步 2 分钟前</span></div><div>{toolbar}</div></div></>; }
export function Pagination() { return <nav className="acl-pagination" aria-label="分页"><span>1–4 / 28</span><Button disabled>上一页</Button><Button className="selected">1</Button><Button>2</Button><Button>3</Button><Button>下一页</Button></nav>; }
export function DataTable({columns,rows,label}:{columns:ReactNode[];rows:ReactNode[][];label:string}) { return <div className="acl-table-wrap"><table aria-label={label}><thead><tr>{columns.map((column,index)=><th key={index}>{column}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{row.map((cell,cellIndex)=><td key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div>; }
export function Checkbox({label,checked,onChange}:{label:string;checked?:boolean;onChange?:(checked:boolean)=>void}) { const [internal,setInternal]=useState(false),value=checked??internal;return <label className="acl-checkbox"><input type="checkbox" checked={value} onChange={event=>{setInternal(event.target.checked);onChange?.(event.target.checked)}}/><span aria-hidden="true">{value&&<Check/>}</span><i className="sr-only">{label}</i></label>; }
export function Slider({value,min,max,onChange,label}:{value:number;min:number;max:number;onChange:(value:number)=>void;label:string}) { return <input className="acl-range" aria-label={label} type="range" value={value} min={min} max={max} onChange={event=>onChange(Number(event.target.value))}/>; }
export function SearchInput({placeholder,onFocus}:{placeholder:string;onFocus?:()=>void}) { return <input placeholder={placeholder} aria-label="全局搜索" onFocus={onFocus}/>; }
export function AvatarButton({children,label}:{children:ReactNode;label:string}) { return <Button className="acl-avatar" aria-label={label}>{children}</Button>; }
