import { useMemo, useState, type ReactNode } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import {
  Accordion, Alert, Avatar, Badge, Button, Card, Checkbox, Chip, Drawer, Dropdown,
  Input, Label, ListBox, NumberField, Pagination, Popover, Radio, RadioGroup,
  SearchField, Select, Separator, Slider, Switch, Table, TableBody, TableCell,
  TableColumn, TableHeader, TableRow, Tabs, TextArea, TextField, Toast, Tooltip, toast,
} from "@heroui/react";
import {
  Activity, AlertCircle, BarChart3, Bell, BookOpen, Bot, Check, ChevronDown,
  ChevronLeft, CircleDollarSign, Clock3, Command, Copy, Database, Download,
  Ellipsis, FileText, Gauge, Heart, HelpCircle, LayoutDashboard, Menu, MessageCircle,
  Moon, MoreHorizontal, Plus, RefreshCw, Search, Send, Settings, Shield, SlidersHorizontal,
  Sparkles, Sun, Upload, UserPlus, Users, Video, WandSparkles, Zap,
} from "lucide-react";
import { useTheme } from "@/lib/use-theme";
import { AreaChart, BarChart, DonutChart, FunnelChart, Heatmap, MetricCard, RadialGauge, ScatterChart, type ChartPoint } from "./charts";
import "./styles.css";

type ModuleId = "dashboard" | "quota" | "community" | "settings";
type AppError = { code: string; msg: string; fieldErrors?: Record<string,string>; requestId?: string; retryable: boolean };

const trend: ChartPoint[] = [
  {label:"06/01",value:72,secondary:28},{label:"06/05",value:86,secondary:35},{label:"06/09",value:79,secondary:31},
  {label:"06/13",value:108,secondary:42},{label:"06/17",value:104,secondary:48},{label:"06/21",value:132,secondary:55},
  {label:"06/25",value:149,secondary:61},{label:"06/30",value:166,secondary:72},
];
const heatValues=Array.from({length:42},(_,index)=>18+((index*17+index%5*11)%82));
const videoRows=[
  {title:"10 分钟看懂生成式 AI",author:"科技研习社",play:"86.4 万",rate:"68%",status:"增长"},
  {title:"城市夜行：上海篇",author:"镜头之外",play:"62.1 万",rate:"74%",status:"稳定"},
  {title:"独立游戏开发日志 #12",author:"像素工坊",play:"48.7 万",rate:"81%",status:"增长"},
  {title:"三分钟料理：夏日凉面",author:"阿满厨房",play:"31.5 万",rate:"57%",status:"关注"},
];
const quotaRows=[
  {team:"视频理解组",quota:"12,000 GB",used:"8,420 GB",threshold:"80%",route:"华东 A",status:"预警"},
  {team:"推荐算法组",quota:"18,000 GB",used:"9,160 GB",threshold:"85%",route:"华北 B",status:"正常"},
  {team:"内容安全组",quota:"8,000 GB",used:"3,920 GB",threshold:"75%",route:"华南 A",status:"正常"},
  {team:"创作工具组",quota:"6,000 GB",used:"5,480 GB",threshold:"90%",route:"公共池",status:"临界"},
];

function HeroSelect({ label, items, className="" }: { label:string;items:Array<[string,string]>;className?:string }) {
  return <Select className={className}><Label>{label}</Label><Select.Trigger><Select.Value/><Select.Indicator/></Select.Trigger><Select.Popover><ListBox>{items.map(([id,text])=><ListBox.Item id={id} key={id}>{text}</ListBox.Item>)}</ListBox></Select.Popover></Select>;
}

function PageHeader({ eyebrow, title, description, actions }: { eyebrow:string;title:string;description:string;actions:ReactNode }) {
  return <><div className="bo-page-header"><div><span>{eyebrow}</span><h1>{title}</h1><p>{description}</p></div><div className="bo-page-actions">{actions}</div></div><div className="bo-context-toolbar"><div><Chip color="success" variant="soft">实时数据</Chip><span>最近同步 2 分钟前</span></div><div><HeroSelect label="时间范围" className="bo-compact-select" items={[["7d","近 7 天"],["30d","近 30 天"],["90d","近 90 天"]]}/><Button variant="outline" size="sm"><RefreshCw size={14}/>刷新</Button><Button variant="ghost" size="sm"><MoreHorizontal size={16}/></Button></div></div></>;
}

function StandardPagination() { return <Pagination size="sm"><Pagination.Summary>1–4 / 28</Pagination.Summary><Pagination.Content><Pagination.Item><Pagination.Previous>上一页</Pagination.Previous></Pagination.Item><Pagination.Item><Pagination.Link isActive>1</Pagination.Link></Pagination.Item><Pagination.Item><Pagination.Link>2</Pagination.Link></Pagination.Item><Pagination.Item><Pagination.Link>3</Pagination.Link></Pagination.Item><Pagination.Item><Pagination.Next>下一页</Pagination.Next></Pagination.Item></Pagination.Content></Pagination>; }

function DashboardPage({ onDetail, error, setError }: { onDetail:(point:ChartPoint)=>void;error:AppError|null;setError:(value:AppError|null)=>void }) {
  return <div className="bo-page"><PageHeader eyebrow="CONTENT INTELLIGENCE" title="企业数据总览" description="围绕视频、用户与收入的全站运营态势。" actions={<><Button variant="outline"><Download size={15}/>导出</Button><Button variant="primary"><Sparkles size={15}/>生成报告</Button></>}/>
    {error&&<Alert status="danger"><Alert.Indicator><AlertCircle size={18}/></Alert.Indicator><Alert.Content><Alert.Title>{error.code}</Alert.Title><Alert.Description>{error.msg}</Alert.Description><Button size="sm" variant="outline" onPress={()=>setError(null)}>重试</Button></Alert.Content></Alert>}
    <section className="bo-kpi-grid"><MetricCard label="总播放量" value="381.2 万" delta="12.8%" points={[22,28,26,36,41,47]} icon={<Video/>}/><MetricCard label="活跃用户" value="28.6 万" delta="8.4%" points={[18,21,29,27,35,39]} icon={<Users/>}/><MetricCard label="新增粉丝" value="42,891" delta="16.1%" points={[14,17,16,24,29,37]} icon={<Heart/>}/><MetricCard label="预估收入" value="¥ 862,430" delta="6.9%" points={[24,25,31,29,34,38]} icon={<CircleDollarSign/>}/></section>
    <section className="bo-primary-grid"><AreaChart title="播放与互动趋势" subtitle="可切换图例、移动十字线并点击下钻" data={trend} series={["播放","互动"]} error={error?.msg} onRetry={()=>setError(null)} onDrilldown={onDetail}/><DonutChart title="流量来源" data={[{label:"首页推荐",value:46,color:"#990099"},{label:"站内搜索",value:24,color:"#d23ad2"},{label:"关注动态",value:18,color:"#7750c7"},{label:"外部链接",value:12,color:"#6b7280"}]}/></section>
    <section className="bo-three-grid"><BarChart title="内容分区表现" data={[{label:"动画",value:82,secondary:61},{label:"游戏",value:74,secondary:66},{label:"知识",value:63,secondary:48},{label:"生活",value:51,secondary:44}]}/><Heatmap title="发布时间热力图" values={heatValues}/><FunnelChart title="用户留存漏斗" data={[{label:"曝光",value:1284000},{label:"播放",value:812000},{label:"互动",value:286000},{label:"关注",value:98400}]}/></section>
    <Card className="bo-table-card"><Card.Header className="bo-card-head"><div><Card.Title>视频表现</Card.Title><Card.Description>内容、完播和异常表现</Card.Description></div><div><Button size="sm" variant="outline"><SlidersHorizontal size={14}/>列设置</Button><Button size="sm" variant="outline" onPress={()=>setError({code:"DASHBOARD_TIMEOUT",msg:"数据服务响应超时，请稍后重试。",requestId:"req_dash_9201",retryable:true})}>模拟错误</Button></div></Card.Header><Card.Content><Table><Table.Content aria-label="视频表现表"><TableHeader><TableColumn>视频</TableColumn><TableColumn>UP 主</TableColumn><TableColumn>播放</TableColumn><TableColumn>完播率</TableColumn><TableColumn>状态</TableColumn><TableColumn>操作</TableColumn></TableHeader><TableBody items={videoRows}>{(row)=><TableRow><TableCell><div className="bo-video-cell"><span><Video/></span><b>{row.title}</b></div></TableCell><TableCell>{row.author}</TableCell><TableCell>{row.play}</TableCell><TableCell>{row.rate}</TableCell><TableCell><Chip color={row.status==="关注"?"warning":"success"} variant="soft">{row.status}</Chip></TableCell><TableCell><Button isIconOnly variant="ghost"><Ellipsis size={16}/></Button></TableCell></TableRow>}</TableBody></Table.Content></Table><StandardPagination/></Card.Content></Card>
  </div>;
}

function QuotaPage({ onConfigure }: { onConfigure:()=>void }) {
  const [error,setError]=useState<AppError|null>(null);return <div className="bo-page"><PageHeader eyebrow="RELAY CAPACITY" title="中转站额度配置" description="统一管理节点、团队额度与溢出策略。" actions={<Button variant="primary" onPress={onConfigure}><Plus size={15}/>新增额度池</Button>}/>{error&&<Alert status="danger"><Alert.Indicator><AlertCircle/></Alert.Indicator><Alert.Content><Alert.Title>{error.code}</Alert.Title><Alert.Description>{error.msg}</Alert.Description></Alert.Content></Alert>}
    <section className="bo-kpi-grid"><MetricCard label="总额度" value="64,000 GB" delta="4.2%" points={[28,30,34,35,38,42]} icon={<Database/>}/><MetricCard label="已分配" value="44,000 GB" delta="9.8%" points={[21,24,25,29,34,39]} icon={<Gauge/>}/><MetricCard label="今日消耗" value="3,842 GB" delta="11.3%" points={[14,20,18,27,33,31]} icon={<Activity/>}/><MetricCard label="预警团队" value="4" delta="2 新增" points={[8,7,9,12,11,16]} icon={<AlertCircle/>}/></section>
    <section className="bo-primary-grid"><AreaChart title="额度消耗与预测" subtitle="实线为消耗，虚线为未来预测" data={trend.map((item,index)=>({...item,value:item.value*30,secondary:(item.secondary??0)*38+index*80}))} series={["实际消耗","预测"]}/><RadialGauge title="总池使用率" value={69} label="44 / 64 TB"/></section>
    <section className="bo-three-grid"><BarChart title="团队额度分布" data={[{label:"视频理解",value:84,secondary:70},{label:"推荐算法",value:64,secondary:51},{label:"内容安全",value:49,secondary:39},{label:"创作工具",value:91,secondary:82}]}/><ScatterChart title="节点质量" data={[{x:24,y:97,label:"华东 A"},{x:42,y:91,label:"华北 B"},{x:68,y:83,label:"新加坡"},{x:35,y:95,label:"华南 A"}]}/><Card className="bo-chart-card"><Card.Header><Card.Title>预警时间线</Card.Title></Card.Header><Card.Content className="bo-timeline">{[["10:42","视频理解组达到 80%"],["09:18","华南 A 延迟恢复"],["昨天","创作工具组自动借用公共池"]].map(([time,text])=><div key={text}><i/><span>{time}</span><b>{text}</b></div>)}</Card.Content></Card></section>
    <Card className="bo-table-card"><Card.Header className="bo-card-head"><div><Card.Title>额度池</Card.Title><Card.Description>28 个团队配置</Card.Description></div><Button size="sm" variant="outline">批量调整</Button></Card.Header><Card.Content><Table><Table.Content aria-label="额度池表"><TableHeader><TableColumn>团队</TableColumn><TableColumn>总额</TableColumn><TableColumn>已用</TableColumn><TableColumn>阈值</TableColumn><TableColumn>路由</TableColumn><TableColumn>状态</TableColumn><TableColumn>操作</TableColumn></TableHeader><TableBody items={quotaRows}>{(row)=><TableRow><TableCell><b>{row.team}</b></TableCell><TableCell>{row.quota}</TableCell><TableCell>{row.used}</TableCell><TableCell>{row.threshold}</TableCell><TableCell>{row.route}</TableCell><TableCell><Chip color={row.status==="正常"?"success":"warning"} variant="soft">{row.status}</Chip></TableCell><TableCell><Button size="sm" variant="ghost" onPress={onConfigure}>编辑</Button></TableCell></TableRow>}</TableBody></Table.Content></Table><div className="bo-table-footer"><Button variant="ghost" onPress={()=>setError({code:"QUOTA_BELOW_USAGE",msg:"新额度不能低于当前已使用额度 8,420 GB。",retryable:false})}>模拟额度错误</Button><StandardPagination/></div></Card.Content></Card>
  </div>;
}

function CommunityPage() {
  const [liked,setLiked]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState<AppError|null>(null);
  const publish=()=>{if(message.includes("内部接口")){setError({code:"POST_REJECTED",msg:"内容包含受限词“内部接口”，请修改后重新发布。",fieldErrors:{content:"请移除受限词"},retryable:false});return;}toast.success("帖子发布成功",{description:"内容已进入社区最新动态。"});setMessage("");};
  return <div className="bo-page"><PageHeader eyebrow="COMMUNITY OPERATIONS" title="社区" description="发布内容、回复用户并治理风险讨论。" actions={<Button variant="primary"><Plus size={15}/>发布帖子</Button>}/>{error&&<Alert status="danger"><Alert.Indicator><AlertCircle/></Alert.Indicator><Alert.Content><Alert.Title>{error.code}</Alert.Title><Alert.Description>{error.msg}</Alert.Description></Alert.Content></Alert>}
    <section className="bo-community-grid"><div className="bo-feed"><Card className="bo-composer"><Card.Header><Avatar size="sm"><Avatar.Fallback>星</Avatar.Fallback></Avatar><div><b>星轨内容科技</b><span>以组织身份发布</span></div></Card.Header><Card.Content><Tabs defaultSelectedKey="rich" variant="secondary"><Tabs.ListContainer><Tabs.List aria-label="编辑模式"><Tabs.Tab id="rich">富文本</Tabs.Tab><Tabs.Tab id="markdown">Markdown</Tabs.Tab></Tabs.List></Tabs.ListContainer><Tabs.Panel id="rich"><TextField isInvalid={Boolean(error?.fieldErrors?.content)}><TextArea value={message} onChange={(event)=>setMessage(event.target.value)} rows={5} placeholder="分享新鲜事，输入“内部接口”可测试错误 msg…"/></TextField></Tabs.Panel><Tabs.Panel id="markdown"><TextField><TextArea rows={5} placeholder="# 使用 Markdown 创作"/></TextField></Tabs.Panel></Tabs><div className="bo-composer-tools"><div><Button isIconOnly variant="ghost"><Upload size={17}/></Button><Button isIconOnly variant="ghost"><Video size={17}/></Button><Button isIconOnly variant="ghost"><BarChart3 size={17}/></Button><Chip size="sm">{message.length}/500</Chip></div><Button variant="primary" onPress={publish}><Send size={15}/>发布</Button></div></Card.Content></Card>
      {[{name:"像素工坊",time:"18 分钟前",text:"独立游戏开发日志第 12 期上线了！这次重点拆解角色状态机与光照优化。",tag:"#独立游戏"},{name:"科技研习社",time:"1 小时前",text:"我们整理了生成式 AI 在视频工作流中的五个真实落地点，欢迎补充。",tag:"#AI创作"}].map((post,index)=><Card className="bo-post" key={post.name}><Card.Header><Avatar size="sm"><Avatar.Fallback>{post.name[0]}</Avatar.Fallback></Avatar><div><b>{post.name}</b><span>{post.time}</span></div><Button isIconOnly variant="ghost"><MoreHorizontal size={17}/></Button></Card.Header><Card.Content><p>{post.text}</p><Chip color="accent" variant="soft">{post.tag}</Chip>{index===0&&<div className="bo-post-media"><WandSparkles size={42}/><span>DEVLOG · EP12</span></div>}</Card.Content><Card.Footer><Button variant={liked&&index===0?"secondary":"ghost"} onPress={()=>index===0&&setLiked(!liked)}><Heart size={16} fill={liked&&index===0?"currentColor":"none"}/>{liked&&index===0?129:128}</Button><Button variant="ghost"><MessageCircle size={16}/>36</Button><Button variant="ghost"><Send size={16}/>分享</Button></Card.Footer></Card>)}</div>
      <aside className="bo-community-aside"><RadialGauge title="社区健康度" value={92} label="稳定"/><AreaChart title="发帖趋势" data={trend.slice(0,6)} series={["帖子","回复"]}/><DonutChart title="热门话题" data={[{label:"游戏",value:34,color:"#990099"},{label:"科技",value:28,color:"#d23ad2"},{label:"生活",value:22,color:"#7750c7"},{label:"其他",value:16,color:"#6b7280"}]}/><Heatmap title="社区活跃" values={heatValues}/></aside></section>
    <Card className="bo-table-card"><Card.Header><Card.Title>举报与治理</Card.Title><Chip color="warning">18 待处理</Chip></Card.Header><Card.Content><Table><Table.Content aria-label="举报内容表"><TableHeader><TableColumn>内容</TableColumn><TableColumn>原因</TableColumn><TableColumn>风险</TableColumn><TableColumn>举报数</TableColumn><TableColumn>处理人</TableColumn><TableColumn>操作</TableColumn></TableHeader><TableBody>{[["疑似引战评论","人身攻击","高","24","林岚"],["外链推广内容","广告垃圾","中","12","周可"],["剧透未标记","社区规范","低","6","未分配"]].map((row)=><TableRow key={row[0]}>{row.map((cell)=><TableCell key={cell}>{cell}</TableCell>)}<TableCell><Button size="sm" variant="outline">处理</Button></TableCell></TableRow>)}</TableBody></Table.Content></Table></Card.Content></Card>
  </div>;
}

function SettingsPage() {
  const [dirty,setDirty]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState<AppError|null>(null);const [orgName,setOrgName]=useState("星轨内容科技");const [orgBio,setOrgBio]=useState("连接创作者、内容和技术的企业工作台。");const save=async()=>{setSaving(true);await new Promise((resolve)=>setTimeout(resolve,900));setSaving(false);if(error){toast.danger(error.msg);return;}setDirty(false);toast.success("设置已保存",{description:"组织配置已同步。"});};
  return <div className="bo-page"><PageHeader eyebrow="ORGANIZATION CONTROL" title="设置" description="组织、安全、通知、集成与权限策略。" actions={<Button variant="outline"><FileText size={15}/>审计日志</Button>}/>{error&&<Alert status="danger"><Alert.Indicator><AlertCircle/></Alert.Indicator><Alert.Content><Alert.Title>{error.code}</Alert.Title><Alert.Description>{error.msg}</Alert.Description></Alert.Content></Alert>}
    <div className="bo-settings-layout"><Card className="bo-settings-nav"><Card.Content>{["组织资料","成员与角色","权限策略","安全","通知","集成","API 与 Webhook","账单","危险区域"].map((item,index)=><Button key={item} variant={index===0?"secondary":"ghost"}>{item}</Button>)}</Card.Content></Card><div className="bo-settings-main"><Card><Card.Header><div><Card.Title>组织资料</Card.Title><Card.Description>展示给所有成员和协作者的信息。</Card.Description></div></Card.Header><Card.Content className="bo-settings-form"><div className="bo-avatar-row"><Avatar size="lg"><Avatar.Fallback>星</Avatar.Fallback></Avatar><Button variant="outline">更换头像</Button></div><TextField isRequired><Label>组织名称</Label><Input value={orgName} onChange={(event)=>{setOrgName(event.target.value);setDirty(true)}}/></TextField><TextField><Label>组织简介</Label><TextArea value={orgBio} rows={3} onChange={(event)=>{setOrgBio(event.target.value);setDirty(true)}}/></TextField><HeroSelect label="默认语言" items={[["zh","简体中文"],["en","English"],["ja","日本語"]]}/><RadioGroup defaultValue="company" variant="secondary"><Label>组织类型</Label><div className="bo-radio-row">{[["company","企业"],["studio","工作室"],["community","社区"]].map(([value,label])=><Radio value={value} key={value}><Radio.Content><Radio.Control><Radio.Indicator/></Radio.Control>{label}</Radio.Content></Radio>)}</div></RadioGroup></Card.Content></Card>
      <section className="bo-settings-charts"><RadialGauge title="安全分数" value={86} label="良好"/><BarChart title="登录活动" data={[{label:"周一",value:62},{label:"周二",value:76},{label:"周三",value:58},{label:"周四",value:91}]}/><AreaChart title="API 使用量" data={trend.slice(0,6)} series={["请求","错误"]}/></section>
      <Card><Card.Header><div><Card.Title>安全与通知</Card.Title><Card.Description>策略修改会记录到审计日志。</Card.Description></div></Card.Header><Card.Content className="bo-switch-list"><Switch defaultSelected onChange={()=>setDirty(true)}><Switch.Content><Switch.Control><Switch.Thumb/></Switch.Control><div><b>强制双因素认证</b><span>所有管理员下次登录时必须配置。</span></div></Switch.Content></Switch><Switch defaultSelected onChange={()=>setDirty(true)}><Switch.Content><Switch.Control><Switch.Thumb/></Switch.Control><div><b>异常登录通知</b><span>向安全联系人发送即时消息。</span></div></Switch.Content></Switch><Accordion variant="surface"><Accordion.Item id="advanced"><Accordion.Heading><Accordion.Trigger>高级会话策略</Accordion.Trigger></Accordion.Heading><Accordion.Panel><Accordion.Body><NumberField defaultValue={12} minValue={1} maxValue={72}><Label>会话有效期（小时）</Label><NumberField.Group><NumberField.DecrementButton/><NumberField.Input/><NumberField.IncrementButton/></NumberField.Group></NumberField></Accordion.Body></Accordion.Panel></Accordion.Item></Accordion></Card.Content></Card>
      <Card className="bo-danger-card"><Card.Header><div><Card.Title>危险区域</Card.Title><Card.Description>这些操作不可撤销。</Card.Description></div></Card.Header><Card.Content><Button variant="danger-soft" onPress={()=>setError({code:"SETTINGS_VERSION_CONFLICT",msg:"设置已被另一位管理员更新，请刷新后重新提交。",requestId:"req_settings_442",retryable:true})}>模拟版本冲突</Button></Card.Content></Card></div></div>
    {dirty&&<div className="bo-save-bar"><div><i/><span>有未保存的更改</span></div><div><Button variant="ghost" onPress={()=>setDirty(false)}>放弃更改</Button><Button variant="primary" isPending={saving} onPress={save}><Check size={15}/>保存设置</Button></div></div>}
  </div>;
}

function QuotaDrawer({ open, onOpenChange }: { open:boolean;onOpenChange:(value:boolean)=>void }) {
  const [threshold,setThreshold]=useState(80);const [saving,setSaving]=useState(false);const save=async()=>{setSaving(true);await new Promise((resolve)=>setTimeout(resolve,900));setSaving(false);onOpenChange(false);toast.success("额度配置已保存",{description:"视频理解组的新规则将在 1 分钟内生效。"});};
  return <Drawer isOpen={open} onOpenChange={onOpenChange}><Drawer.Backdrop><Drawer.Content placement="right"><Drawer.Dialog><Drawer.Header><Drawer.Heading>配置额度池</Drawer.Heading><Drawer.CloseTrigger/></Drawer.Header><Drawer.Body className="bo-drawer-form"><TextField isRequired><Label>额度池名称</Label><Input defaultValue="视频理解组"/></TextField><HeroSelect label="适用团队" items={[["video","视频理解组"],["recommend","推荐算法组"],["safety","内容安全组"]]}/><RadioGroup defaultValue="month" variant="secondary"><Label>结算周期</Label><div className="bo-radio-row"><Radio value="day"><Radio.Content><Radio.Control><Radio.Indicator/></Radio.Control>每日</Radio.Content></Radio><Radio value="month"><Radio.Content><Radio.Control><Radio.Indicator/></Radio.Control>每月</Radio.Content></Radio><Radio value="custom"><Radio.Content><Radio.Control><Radio.Indicator/></Radio.Control>自定义</Radio.Content></Radio></div></RadioGroup><NumberField defaultValue={12000} minValue={8420}><Label>总额度（GB）</Label><NumberField.Group><NumberField.DecrementButton/><NumberField.Input/><NumberField.IncrementButton/></NumberField.Group></NumberField><div><Label>预警阈值：{threshold}%</Label><Slider value={threshold} onChange={(value)=>setThreshold(Number(value))} minValue={50} maxValue={95}><Slider.Track><Slider.Fill/><Slider.Thumb/></Slider.Track></Slider></div><HeroSelect label="节点路由" items={[["east","华东 A"],["north","华北 B"],["public","公共池"]]}/><Switch defaultSelected><Switch.Content><Switch.Control><Switch.Thumb/></Switch.Control>自动续期</Switch.Content></Switch><Accordion variant="surface"><Accordion.Item id="advanced"><Accordion.Heading><Accordion.Trigger>高级限制</Accordion.Trigger></Accordion.Heading><Accordion.Panel><Accordion.Body>并发上限 40，超额时借用公共池。</Accordion.Body></Accordion.Panel></Accordion.Item></Accordion></Drawer.Body><Drawer.Footer><Button variant="ghost" onPress={()=>onOpenChange(false)}>取消</Button><Button variant="primary" isPending={saving} onPress={save}>保存配置</Button></Drawer.Footer></Drawer.Dialog></Drawer.Content></Drawer.Backdrop></Drawer>;
}

export default function BiliOpsHeroUI() {
  const {theme,toggleTheme}=useTheme();const navigate=useNavigate();const location=useLocation();const module=(location.pathname.split("/").pop()||"dashboard") as ModuleId;
  const [collapsed,setCollapsed]=useState(false);const [drawerOpen,setDrawerOpen]=useState(false);const [detail,setDetail]=useState<ChartPoint|null>(null);const [dashboardError,setDashboardError]=useState<AppError|null>(null);const [searchOpen,setSearchOpen]=useState(false);
  const go=(id:ModuleId)=>navigate(`/lab/heroui/${id}`);const nav=[{id:"dashboard" as const,label:"企业数据总览",icon:<LayoutDashboard/>},{id:"quota" as const,label:"中转站额度",icon:<Gauge/>},{id:"community" as const,label:"社区",icon:<MessageCircle/>},{id:"settings" as const,label:"设置",icon:<Settings/>}];
  return <div className={`bo-app ${collapsed?"is-collapsed":""}`} data-theme={theme}><Toast.Provider/><header className="bo-topbar"><div className="bo-logo"><span><Bot/></span><b>BiliOps</b><Chip size="sm" color="accent">HeroUI</Chip></div><div className="bo-top-search"><SearchField onFocus={()=>setSearchOpen(true)} onBlur={()=>setTimeout(()=>setSearchOpen(false),150)}><SearchField.Group><SearchField.SearchIcon/><SearchField.Input placeholder="搜索视频、用户、配置…"/><SearchField.ClearButton/></SearchField.Group></SearchField>{searchOpen&&<Card className="bo-command"><Card.Content><span>快速跳转</span>{nav.map((item)=><Button key={item.id} variant="ghost" onPress={()=>go(item.id)}>{item.icon}{item.label}<kbd>↵</kbd></Button>)}</Card.Content></Card>}</div><div className="bo-top-actions"><Dropdown><Dropdown.Trigger className="button button--md button--primary"><Plus size={16}/>创建<ChevronDown size={14}/></Dropdown.Trigger><Dropdown.Popover placement="bottom end"><Dropdown.Menu onAction={(key)=>toast.info(`已选择：${String(key)}`)}><Dropdown.Item id="upload"><Upload/>上传视频</Dropdown.Item><Dropdown.Item id="quota"><Gauge/>配置额度</Dropdown.Item><Dropdown.Item id="post"><MessageCircle/>发布帖子</Dropdown.Item><Dropdown.Item id="invite"><UserPlus/>邀请成员</Dropdown.Item></Dropdown.Menu></Dropdown.Popover></Dropdown><Popover><Popover.Trigger><Button isIconOnly variant="ghost"><Badge.Anchor><Bell size={18}/><Badge color="danger" size="sm">3</Badge></Badge.Anchor></Button></Popover.Trigger><Popover.Content placement="bottom end"><Popover.Dialog className="bo-notifications"><Popover.Heading>通知</Popover.Heading><div><b>额度即将耗尽</b><span>视频理解组已使用 80%</span></div><div><b>新举报待处理</b><span>社区收到 18 条举报</span></div></Popover.Dialog></Popover.Content></Popover><Button isIconOnly variant="ghost" onPress={toggleTheme}>{theme==="dark"?<Sun/>:<Moon/>}</Button><Avatar size="sm"><Avatar.Fallback>HX</Avatar.Fallback></Avatar></div></header>
    <aside className="bo-sidebar"><div className="bo-workspace"><Avatar size="sm"><Avatar.Fallback>星</Avatar.Fallback></Avatar>{!collapsed&&<div><b>星轨内容科技</b><span>企业工作区</span></div>}</div><nav>{nav.map((item)=><Tooltip key={item.id}><Tooltip.Trigger><Button className={module===item.id?"is-active":""} variant={module===item.id?"secondary":"ghost"} onPress={()=>go(item.id)}>{item.icon}{!collapsed&&<span>{item.label}</span>}{!collapsed&&item.id==="community"&&<Chip size="sm" color="warning">18</Chip>}</Button></Tooltip.Trigger>{collapsed&&<Tooltip.Content placement="right">{item.label}</Tooltip.Content>}</Tooltip>)}</nav><div className="bo-sidebar-bottom"><Button variant="ghost"><HelpCircle/>{!collapsed&&"帮助与文档"}</Button><Button variant="ghost"><Activity/>{!collapsed&&"系统状态"}</Button><Separator/><Button variant="ghost" onPress={()=>setCollapsed(!collapsed)}><ChevronLeft className={collapsed?"rotate-180":""}/>{!collapsed&&"收起侧栏"}</Button></div></aside>
    <main className="bo-content">{module==="dashboard"&&<DashboardPage error={dashboardError} setError={setDashboardError} onDetail={setDetail}/>} {module==="quota"&&<QuotaPage onConfigure={()=>setDrawerOpen(true)}/>} {module==="community"&&<CommunityPage/>} {module==="settings"&&<SettingsPage/>}</main>
    <QuotaDrawer open={drawerOpen} onOpenChange={setDrawerOpen}/>
    <Drawer isOpen={Boolean(detail)} onOpenChange={(open)=>!open&&setDetail(null)}><Drawer.Backdrop><Drawer.Content placement="right"><Drawer.Dialog><Drawer.Header><Drawer.Heading>{detail?.label} 数据下钻</Drawer.Heading><Drawer.CloseTrigger/></Drawer.Header><Drawer.Body><div className="bo-detail-value"><span>播放量</span><strong>{detail?.value.toLocaleString()}</strong></div><Alert status="warning"><Alert.Indicator><Zap/></Alert.Indicator><Alert.Content><Alert.Title>检测到异常增长</Alert.Title><Alert.Description>首页推荐流量较日均水平高 28%，主要来自 3 个科技类视频。</Alert.Description></Alert.Content></Alert><BarChart title="来源拆解" data={[{label:"首页",value:82},{label:"搜索",value:48},{label:"关注",value:31},{label:"外链",value:18}]}/></Drawer.Body><Drawer.Footer><Button variant="outline" onPress={()=>setDetail(null)}>关闭</Button><Button variant="primary">查看完整报告</Button></Drawer.Footer></Drawer.Dialog></Drawer.Content></Drawer.Backdrop></Drawer>
  </div>;
}
